---

networks:
  stack-php:
    # fixer le nom
    name: stack-php
    driver: bridge
    # Internet Protocol Adress Management
    ipam:
      config:
        - subnet: 172.18.0.0/24
          gateway: 172.18.0.1

# déclarer les volumes nommés!!!
volumes:
  db_data:
    name: db_data
  nfs-vol-db:
    name: nfs-vol-db
    # les éléments du serveur NFS sont téléchargés dans l'emplacement local (/var/lib/docker/volumes/...)
    driver: local
    # configuraiton du volumes dépendent de la technologie attendues
    driver_opts:
      type: nfs
      # nomenclature NFS
      o: addr=docker.lan,ro
      device: :/mnt/nfs-dir/initdb.d
  nfs-vol-php:
    name: nfs-vol-php
    driver: local
    driver_opts:
      type: nfs
      o: addr=docker.lan,ro
      device: :/mnt/nfs-dir/app
  nfs-vol-web:
    name: nfs-vol-web
    driver: local
    driver_opts:
      type: nfs
      o: addr=docker.lan,ro
      device: :/mnt/nfs-dir/nginx-conf.d

# service = ensemble de replicas (réplications) d'une config. de conteneur, dispatchés dans l'infra
services:
  # nom des services
  db:
    # radical des noms des replicas
    container_name: stack-php-mariadb
    image: mariadb:11.7-ubi
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - stack-php
    volumes:
      # - ./mariadb-init.sql:/docker-entrypoint-initdb.d/mariadb-init.sql:ro
      - nfs-vol-db:/docker-entrypoint-initdb.d:ro
      - db_data:/var/lib/mysql
    
  php:
    container_name: stack-php-fpm
    image: bitnami/php-fpm:8.4-debian-12
    restart: unless-stopped
    networks:
      - stack-php
    volumes:
      # - ./index.php:/srv/index.php:ro
      - nfs-vol-php:/srv:ro
    depends_on:
      - db
  
  web:
    container_name: stack-php-nginx
    image: nginx:1.27.4-bookworm
    restart: unless-stopped
    networks:
      - stack-php
    volumes:
      # - ./vhost.conf:/etc/nginx/conf.d/vhost.conf:ro
      - nfs-vol-web:/etc/nginx/conf.d:ro
    ports:
      - 8080:80
    depends_on:
      - php