---

networks:
  stack-php:
    # fixer le nom
    name: stack-php
    driver: bridge
    # Internet Protocol Adress Management
    ipam:
      config:
        - subnet: 172.18.0.0/24
          gateway: 172.18.0.1

# déclarer les volumes nommés!!!
volumes:
  db_data:
    name: db_data


# service = ensemble de replicas (réplications) d'une config. de conteneur, dispatchés dans l'infra
services:
  # nom des services
  db:
    # radical des noms des replicas
    container_name: stack-php-mariadb
    image: mariadb:11.7-ubi
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - stack-php
    volumes:
      - ./mariadb-init.sql:/docker-entrypoint-initdb.d/mariadb-init.sql:ro
      - db_data:/var/lib/mysql
    
  php:
    container_name: stack-php-fpm
    image: bitnami/php-fpm:8.4-debian-12
    restart: unless-stopped
    networks:
      - stack-php
    volumes:
      - ./index.php:/srv/index.php:ro
  
  web:
    container_name: stack-php-nginx
    image: nginx:1.27.4-bookworm
    restart: unless-stopped
    networks:
      - stack-php
    volumes:
      - ./vhost.conf:/etc/nginx/conf.d/vhost.conf:ro
    ports:
      - 8080:80