## nous allons utiliser une image debian:12-slim
FROM debian:12-slim

## documenter l'image


## ajouter un dossier /opt/tomcat
# RUN mkdir /opt/tomcat

## injecter le fichier https://downloads.apache.org/tomcat/tomcat-9/v9.0.98/bin/apache-tomcat-9.0.98.tar.gz dans ce dossier
# ADD https://downloads.apache.org/tomcat/tomcat-9/v9.0.98/bin/apache-tomcat-9.0.98.tar.gz /opt/tomcat

## décomprésser dans ce dossier sans dossier intermédiaire 
# RUN curl https://downloads.apache.org/tomcat/tomcat-9/v9.0.98/bin/apache-tomcat-9.0.98.tar.gz -o /opt/tomcat/apache-tomcat-9.0.98.tar.gz
# RUN tar -xzvf /opt/tomcat/apache-tomcat-9.0.98.tar.gz -C /opt/tomcat --strip-components=1

# RUN rm -f /opt/tomcat/apache-tomcat-9.0.98.tar.gz


## installer java (yum)
# RUN yum update -q && yum install -y -q java
# et nettoyer le dépôt
# RUN yum clean all && rm -rf /var/cache/yum

## ajouter un utilisateur tomcat avec le dossier /opt/tomcat comme home et un group tomcat
# RUN useradd -M -d /opt/tomcat -U tomcat

## changer le home de l'image vers /opt/tomcat/webapps
# WORKDIR /opt/tomcat/webapps

## télécharger l'application sample https://tomcat.apache.org/tomcat-10.1-doc/appdev/sample/sample.war dans le dossier home 
# ADD https://tomcat.apache.org/tomcat-10.1-doc/appdev/sample/sample.war .

## spécifier le propriétaire et groupe à tomcat 
# RUN chown -R tomcat:tomcat /opt/tomcat

## changer l'utilisateur à tomcat
# USER tomcat

## persister le dossier home pour accéder ou sauvegarder les apps
# VOLUME [ "/opt/tomcat/webapps" ]

## pour communiquer avec httpd avec le port 8080
# EXPOSE 8080

## exécuter de manière statique (sans substitution) le binaire en foreground catalina.sh vs startup.sh ???
# ENTRYPOINT [ "/opt/tomcat/bin/catalina.sh" ]

## ajouter la sous commande pour lancer en one shot run ou start ???
# CMD ["/opt/tomcat/bin/catalina.sh", "run" ]
