---
# --- signifie "ici document yaml donc un arbre de clé"
# version de la syntaxe != version de docker-compose (dc)
version: '3.9'

# service = conteneur
services:
  # nom du service (arbitraire)
  app_web:
    container_name: app_web
    image: nginx:1.22
    restart: unless-stopped
    ports:
      - 8080:80
    # volumes:
    #   # - type: bind
    #   #   source: /vagrant/confs/nginx/app_php.conf
    #   #   target: /etc/nginx/conf.d/app_php.conf
    #   #   read_only: true
    #   - /vagrant/confs/nginx/app_php.conf:/etc/nginx/conf.d/app_php.conf:ro
    networks:
      # association avec ip par défaut
      - stack_php
      # association avancée
      # stack_php:
      #   ipv4_address: 172.19.0.4
    # idem Dockerfile
    labels:
      - author=matt
      - stack=stack_php
      - stack.version=1.0.0
    # tags pour lancer le docker compose
    profiles:
      - debug
      - prod



networks:
  stack_php:
    driver: bridge
    name: stack_php
    # config avancée
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/24
          gateway: 172.19.0.1